[versions]
compose-plugin = "1.12.0"
compose-material3 = "1.9.0"
# Kotlin
kotlin = "2.4.20"
buildconfig = "6.0.10"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
# logback
logback = "1.6.3"
# https://github.com/h2database/h2database
h2 = "2.5.250"
# https://github.com/JetBrains/Exposed
exposed = "1.5.0"
# https://github.com/KoalaPlot/koalaplot-core
# https://koalaplot.github.io/
koalaPlot = "0.12.1"
# https://github.com/brettwooldridge/HikariCP
hikariCP = "7.1.0"

# https://conveyor.hydraulic.dev/21.0/configs/maven-gradle/#gradle
conveyor = "2.0"

[libraries]
# logback
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# ktx
# ktx-coroutine
kotlinx-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# h2 driver
h2db = { module = "com.h2database:h2", version.ref = "h2" }

# exposed
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-javaTime = { group = "org.jetbrains.exposed", name = "exposed-java-time", version.ref = "exposed" }

# koalaPlot
koalaPlot-core = { group = "io.github.koalaplot", name = "koalaplot-core", version.ref = "koalaPlot" }

hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikariCP" }

[bundles]
exposed = ["exposed-core", "exposed-dao", "exposed-jdbc", "exposed-javaTime"]

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
conveyor = { id = "dev.hydraulic.conveyor", version.ref = "conveyor" }
